version: '3.8'

services:
  ros-master:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: unless-stopped

  prl:
    image: prl/ur5:latest
    build:
      context: docker
      dockerfile: prl_ur5.Dockerfile
    networks:
      - ros
    restart: unless-stopped
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    # Share your user to the container in order to access your x11
    user: ${UID}:${GID} 
    volumes: 
      # Share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    command: stdbuf -o L roslaunch prl_ur5_run $PRL_COMMAND

  # Uncommment this part to add your own Dockerfile
  # my-project:
  #   image: awesome:latest
  #   build:
  #     context: awesome
  #     dockerfile: Dockerfile
  #   networks:
  #     - ros
  #   volumes:
  #     - scratch:/scratch
  #   restart: unless-stopped
  #   depends_on:
  #     - prl
  #   environment:
  #     - "ROS_MASTER_URI=http://ros-master:11311"

networks:
  ros:
    driver: bridge

volumes:
  scratch:
    # Uncomment this part to mount your persistent volume. SCRATCH must be setup in a .env file
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: $SCRATCH
