version: '3.8'

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: prl-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: unless-stopped

  prl:
    image: prl/ur5:noetic
    container_name: prl-ur5
    build:
      context: docker
      dockerfile: prl_ur5.Dockerfile
    networks:
      - ros
    restart: unless-stopped
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_LOG_DIR=/log"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    devices:
     - "/dev/dri:/dev/dri"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - log:/log
    command: stdbuf -o L roslaunch prl_ur5_run $PRL_COMMAND

  # Edit this part to fit your need.
  project:
    image: project:latest
    container_name: my-project
    build:
      context: docker
      dockerfile: $PROJECT_IMAGE
    # Uncomment this part if you want to use a GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    tty: true
    networks:
      - ros
    volumes:
      - scratch:/scratch
      - log:/log
    restart: unless-stopped
    depends_on:
      - prl
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_LOG_DIR=/log"

networks:
  ros:
    name: ros
    driver: bridge

volumes:
  # Create a persistent volume for ROS log.
  # LOG_DIR must be setup in a .env file
  log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $LOG_DIR

  # Create a persistent volume for your code or data.
  # SCRATCH_DIR must be setup in a .env file
  scratch:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $SCRATCH_DIR
